FROM node:18-alpine
MAINTAINER Navya_Sri 06/05/2026
LABEL nodejs deployment
EXPOSE 3000
WORKDIR myapp/
COPY package*.json .
RUN npm install
COPY . .

ENV PORT=3000
ENV HOST=0.0.0.0
CMD ["node","app.js"]
